services:
    jackal:
        build:
            context: .
        depends_on:
            - monitor
            - db
        volumes:
            - /etc/suricata:/etc/suricata:ro
            - /var/log/suricata:/var/log/suricata:ro
        environment:
            - MONGO_URI=root:example@db:27017
            - MAX_LOGS=1000
            - NETWORK_MONITOR=http://monitor:5000
            - NETWORK_MONITOR_ACTIVE=true
            - NODE_ENV=development
        networks:
            - internal
    nginx:
        build:
        context: nginx-basic-auth
        ports:
            - "80:80"
        depends_on:
            - frontend
        environment:
            - FORWARD_HOST=jackal
            - FORWARD_PORT=3000
            - BASIC_USERNAME=rusec
            - BASIC_PASSWORD=CHANGEME
        networks:
            - internal

    monitor:
        build:
            context: ./monitor
        # ports:
        #     - "5000:5000"
        networks:
            - internal
    db:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo:/var/lib/mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        networks:
            - internal

volumes:
    mongo:
        driver: local

networks:
    internal:
