
services:
    jackal:
        build:
            context: .
        ports:
            - "3000:3000"
        depends_on:
            - monitor
        volumes:
            - /etc/suricata:/etc/suricata:ro
            - /var/log/suricata:/var/log/suricata:ro

    monitor:
        build:
            context: ./monitor
        ports:
            - "5000:5000"
        volumes:
            - /var/log/monitor:/var/log/monitor:ro
