# Use the official Python image
FROM python:3.9

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy app files
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port
EXPOSE 5000

# Start the app
CMD [ "python", "app.py" ]
